services:
  - type: web
    name: hashbet-backend
    env: node
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://hashbetcelo.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CELO_CHAIN_ID
        value: "42220"
      - key: CONTRACT_ADDRESS
        value: "0xeeD34740a6032fD6A6f3e668752f5d4bD54C95F8"
      - key: CELO_RPC_URL
        value: "https://forno.celo.org"
      - key: PAYMENT_TOKEN_ADDRESS
        value: "0x765de816845861e75a25fca122bb6898b8b1282a"
      - key: PAYMENT_TOKEN_SYMBOL
        value: "cUSD"
      - key: PAYMENT_TOKEN_DECIMALS
        value: "18"
